name: Shell Commands

on: 
  repository_dispatch:
    types:
      - build
  pull_request:
    types:
      - opened
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: multiline script
        run: |
          node -v
          npm -v
  run-checkout-command:
    runs-on: ubuntu-latest
    steps:
      - name: log files
        run: ls
      - name: git action checkout 
        uses: actions/checkout@v2
      - name: log files after checkout
        run: ls
      - name: Simple js action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: John
      - name: Log greet
        run: echo "${{steps.greet.outputs.time}}"
